trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'bottl_Repo'
  
steps:
- task: Maven@2
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'

- task: Docker@2
  displayName: Build and Push image
  inputs:
    command: buildAndPush
    containerRegistry: 'docker hub'
    repository: solutionsdigitalteam/$(imageName)
    tags: |
        latest
